### PR TITLE
Add logging and some CLI args

### PR DESCRIPTION
**Pull request by redzic**
Changes:
- Some checking of input file (if it even exists, the format, so you can't for example input a `.png` file)
- Fancier, configurable (through CLI argument) logging with the `log` and `simplelog` crates
- More precise bitrate, e.g. store bitrate at 96,000 and pass it to ffmpeg as 96,000 and do calculations with that level of precision, instead of initial bitrate being 96 and passing to ffmpeg as 96K
- Extra CLI options, `-l`/`--log` to set log level, `-m`/`--model` to set location of model that is passed to visqol, and `--keep`, which keeps the temporary folder (otherwise it deletes it at the end)
- Some debug logging, if `-l DEBUG` is passed then some extra logging happens (specifically of the output of visqol, at least right now)
- Other small changes

### CODE REVIEW

**Comment by master-of-zen** [comment]
I pushed embedded visqol model :(, resolving

**Comment by master-of-zen** [comment]
Resolved, thanks @redzic :+1:

**Comment by redzic** [comment]
Cool! I think I'm gonna open another PR to make the `--model` flag optional, and if it isn't provided, then it just uses the default (embedded) model. Also, I don't think it actually uses the embedded model right now, since it passes `model.to_str().unwrap()` to visqol, which is the CLI option.

**Comment by master-of-zen** [comment]
Yep, I just resolved, `--model` must be optional

**Pull request merged**
